### PR TITLE
Do not use testglue for nSIM ELF32 toolchain tests

### PR DESCRIPTION
**Pull request by anthony-kolesov**
ARC newlib doesn't have function _exit, however Dejagnu testglue is intended
to wrap around it. Thus function _exit() gets created even though it is
never called. When performing execution tests Dejagnu sets breakpoints at
"exit" functions: abort() and _exit(), if it couldn't set at _exit() then at
exit(). That latter case should be applied to ARC, but instead we get
breakpoint at function created by testglue which is never called.

This patch explicitly request Dejagnu to not use testglue. GCC testsuite
uses `board_info needs_status_wrapper` to define whether testglue is needed.
Upstream binutils doesn't have this change, so binutils testsuite must be
patched for this to work properly.

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi Anton,

Is it really as simple as this? I thought ARC needed the wrapper for targets other than the simulator and Linux. Have you tested this with xCAM or the Opella GDB server?

if it works with these targets (might be hard to test for Opella at the moment, but at least xCAM), please apply to mainline and 4.8.

**Comment by anthony-kolesov** [comment]
Hi Jeremy,

I disable testglue only for nsim_gdb targets. Do we have a board file for xCAM?

**Comment by jeremybennett** [comment]
I _think_ you might be able to disable for V1 sim targets as well. I believe it supports host file I/O, so should work without a wrapper.

I don't have an xCAM set up here. It is the one system I though that might not support host file I/O.

I should have noticed it was only the nsim board you were changing. Please make the change (mainline and 4.8).

**Comment by anthony-kolesov** [comment]
With latest commit to arc-sim.exp from Joern (in arc-4.8-dev) status wrapper should be already disabled, I think, because he disabled options which cause the need for wrapper.

**Pull request merged**
