### PR TITLE
Anton docs update

### PR DESCRIPTION
**Pull request by anthony-kolesov**

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi Anton,

I don't think this is quite right. How about this for the main section:

> The branch name corresponds to the development for the various ARC releases.
> - arc-mainline-dev is the mainline development branch
> - arc-4.8-dev is the development branch for the 4.8 tool chain release
> - arc-4.4-dev is the development branch for the 4.4 tool chain release
> 
> These branches are under active development, and while the top of each branch
> should build and run reliably, they have not necessarily been through full
> release testing.
> 
> Within each branch there are points where the whole development has been put
> through comprehensive release testing. These are marked using git _tags_. For
> example tag `arc_4_8-R1` means that this is the first release of the Synopsys
> DesignWare ARC 4.8 tool chain, while tag `arc_4_8-R1.2` means this is the
> second minor patch set to the first release of the ARC 4.8 tool chain.
> 
> These tagged stable releases have been through full release testing, and known
> issues are documented in a Synopsys release notes.
> 
> In general the tool chain release numbering corresponds to the version of GCC
> within that tool chain release. Active development is generally carried out on
> the mainline branch, with changes back-ported to earlier release branches if
> appropriate.

The changes  in the Prequisites section are not in the right place. You don't
want to use the tags before the arc-clone-all.sh command. Instead the change
is at the bottom. I suggest extend as follows:

> Checkout the `toolchain` repository to the desired branch or tag, for example
> to get the mainline development branch use:
> 
>  cd toolchain
>  git checkout arc-mainline-dev
> 
> while to get the 4.8 version 1 stable release use:
> 
>  cd toolchain
>  git checkout arc_4_8-R1

**Comment by anthony-kolesov** [comment]
Updated.

**Comment by jeremybennett** [comment]
Looks good. Please commit and backport to all other branches.

Thanks,

Jeremy

**Comment by anthony-kolesov** [comment]
Commited:
arc-mainline-dev: abc32c27143eecc322ab5ccee8288e792cd3b432
arc-4.8-dev: 5a2511819ca4b6c68cf5a5210eea1dea4dbdaa44
arc-4.8-stable: 37bd6679d81c1a1e4ae00bfb020122f2732a2fff

**Pull request closed without merging**
