### PR TITLE
Ensure that function _exit() is not created by testglue

### PR DESCRIPTION
**Pull request by anthony-kolesov**
ARC newlib doesn't have function _exit, however testglue is intended to wrap around it. This function gets created even though it is never called. When performing execution tests Dejagnu sets breakpoints at "exit" functions: abort() and _exit(), if it couldn't set at _exit() then at exit(). That latter case should be applied to ARC, but instead we get breakpoint at function created by testglue which is never called. To resolve this without altering generic code following is done: first we compile wrapper with -ffunction-sectionsi so that each function is compiled into it's own section, then we link with --gc-section, so that unneeded sections will be excluded from final application. Thus application will not include stale _exit() function that will confuse Dejagnu.

### CODE REVIEW

**Comment by amylaar** [comment]
Adding -Wl,--gc-sections is no good, it perturbs the test results.
We couldn't be using the wrapper in the first place.

**Comment by anthony-kolesov** [comment]
This should be possible for GCC testsuite. But not for the binutils testsuite. It just uses testglue without asking for tester opinion. I think I can change this, but that would be a change is upstream code, so I need a blessing from Jeremy and/or Simon.

For the reference `binutils/binutils/testsuite/binutils-all/objcopy.exp` has this:

```
proc copy_setup { } {
    global srcdir
    global subdir
    global gcc_gas_flag
    global test_prog
    global host_triplet

    set res [build_wrapper testglue.o]
    set flags { debug }
```

Nothing like GCC's `${tool}_maybe_build_wrapper`.

**Comment by amylaar** [comment]
Quoting Anthony Kolesov notifications@github.com:

> This should be possible for GCC testsuite. But not for the binutils  
> testsuite. It just uses testglue without asking for tester opinion.  
> I think I can change this, but that would be a change is upstream  
> code, so I need a blessing from Jeremy and/or Simon.

Another approach you can explore is to build the wrapper differently,
i.e. put the _exit wrapper into a seperate object file, and that in
a library.

Unless nsim is fixed to return exit statuses, you might still need this
for nsim support.

**Comment by anthony-kolesov** [comment]
I'm pretty sure that the way how dejagnu works it is better to make sure that it hits breakpoint at exit(). So the question is how to ensure that _exit doesn't exist in target. In case of upstream code it is possible to just make an exception  for ARC so that it wouldn't be wrapping around _exit at all. Some of the other targets already has their own specifics "ifs" there in `proc build_wrapper`.

**Comment by jeremybennett** [comment]
These wrappers cause problems in various ways on a number of architectures. They are a solution to the problem of testing embedded architectures without printf style I/O.

Ultimately it's a bug in ARC newlib. Newlib requires _exit to be defined as a system call, and we don't (because our implementation is so very old). The correct fix is therefore in newlib, ideally as part of a more general tidy up to separate out a libgloss 

My solution was to provide overrides of the relevant expect/tcl functions, which is a more general solution than imposing specific options. Was there a reason why this approach did not work for you?

**Comment by anthony-kolesov** [comment]
Custom functions work, the problem is that if Dejagnu gets updated we don't get updated function. Also copying 300 LOC function just to edit 3 lines seems like a bad design. That's a shame that Dejagnu doesn't provide a clear way to override the name of _exit(), while hiding this logic in such a big function. I consider current state to be a workaround that shouldn't be kept forever.

If required update to newlib will be done in a foreseeable future (like 4.8-R3), then I'll be happy to keep current solution. Otherwise we should come up with something more permanent, like patch to binutils testsuite or to dejagnu, etc.

**Comment by jeremybennett** [comment]
Let's leave current situation, but please file a STAR to get _exit added to newlib. At some stage, someone may notice it's missing from the newlib port and ask questions :)

I agreed 300 lines to fix 3 lines is big, but DejaGnu is pretty stable, so it is unlikely to change.

**Comment by amylaar** [comment]
Quoting Jeremy Bennett notifications@github.com:

> I agreed 300 lines to fix 3 lines is big, but DejaGnu is pretty  
> stable, so it is unlikely to change.

The way to make it change is to submit a patch.

**Comment by anthony-kolesov** [comment]
Another approach has been used, closing this request.
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/pull/20

**Pull request closed without merging**
