### PR TITLE
Refactor dejagnu scripts to fix all stylistic and functional errors

### PR DESCRIPTION
**Pull request by qwersem**
This PR fix all stylistic and functional errors of dejagnu scripts. Besides that, PR includes itself a Tcl linter to CI for dejagnu scripts related to ARC and nSIM to avoid such errors in the future. This linter matches with [GNU Coding Standards (Chapter 5)](http://www.literateprogramming.com/gnustandards.pdf).

### CODE REVIEW

**Comment by shahab-vahedi** [comment]
I see irrelevant commits here in this PR.

**Comment by qwersem** [comment]
@shahab-vahedi , which one? 29d29aaafcd93a6299e61a1c7d996f0b7dbaa0f0 ?

**Comment by shahab-vahedi** [comment]
27ce96e6b622cb5061b99efc2d3f30baa9929d31
e54cf2fad8632c9d164574a5508fab3cabbe2e65
29d29aaafcd93a6299e61a1c7d996f0b7dbaa0f0

The first one is absolutely irrelevant.
The last two should go yet in a separate PR.

**HOWEVER**

If we merge this with a "rebase" then it should be fine. If we really create a "merge" then they should go separately.

**Review by shahab-vahedi — APPROVED** [review]
I believe I said all that needed to be said.

**Review by shahab-vahedi — APPROVED** [review]

**Pull request merged**
